<script lang="ts">
import { Body, Layout, Link, ModalContent } from "@supertoolmake/bbui"
import type { Datasource } from "@supertoolmake/types"
import { createEventDispatcher } from "svelte"
import { PHOSPHOR_ICONS, SVELTE_COMPONENT_ICONS } from "@/helpers/integrationIcons"
import { IntegrationNames } from "@/constants"
import { appStore, datasources as datasourcesStore } from "@/stores/builder"
import TableOrViewOption from "./TableOrViewOption.svelte"
import type { SourceOption } from "./utils"
import { makeTableOption } from "./utils"

export let onConfirm: () => Promise<void> | void
export let selectedTablesAndViews: SourceOption[]

const dispatch = createEventDispatcher()
const getTablesAndViews = (datasource: Datasource, datasources: Datasource[]) => {
  let tablesAndViews: SourceOption[] = []
  const tables = Array.isArray(datasource.entities)
    ? datasource.entities
    : Object.values(datasource.entities ?? {})

  for (const table of tables) {
    if (table._id === "ta_users") {
      continue
    }

    const formattedTable = makeTableOption(table, datasources)

    tablesAndViews = tablesAndViews.concat([formattedTable])
  }

  return tablesAndViews
}

const getDatasources = (rawDatasources: Datasource[]) => {
  const datasources = []

  for (const rawDatasource of rawDatasources) {
    if (rawDatasource.source === IntegrationNames.REST || !rawDatasource.entities) {
      continue
    }

    if (SVELTE_COMPONENT_ICONS[rawDatasource.source]) {
      const { component, color } = SVELTE_COMPONENT_ICONS[rawDatasource.source]
      datasources.push({
        name: rawDatasource.name,
        iconComponent: component,
        iconColor: color,
        tablesAndViews: getTablesAndViews(rawDatasource, rawDatasources),
      })
    } else {
      const iconData = PHOSPHOR_ICONS[rawDatasource.source] || PHOSPHOR_ICONS.CUSTOM
      const weightClass = iconData.weight ? ` ph-${iconData.weight}` : ""
      datasources.push({
        name: rawDatasource.name,
        iconClass: `ph-${iconData.name}${weightClass}`,
        iconColor: iconData.color,
        tablesAndViews: getTablesAndViews(rawDatasource, rawDatasources),
      })
    }
  }

  return datasources
}

const toggleSelection = (tableOrView: SourceOption) => {
  dispatch("toggle", tableOrView)
}

$: datasources = getDatasources($datasourcesStore.list)

let dataUrl = ""
$: dataUrl = $appStore.appId ? `/builder/workspace/${$appStore.appId}/data` : ""
</script>

<ModalContent
  title="Autogenerated screens"
  confirmText="Next"
  cancelText="Back"
  {onConfirm}
  disabled={!selectedTablesAndViews.length}
  size="L"
>
  {#if datasources?.length}
    <Body size="S">
      Select which tables you would like to use to create your screens
    </Body>
    <Layout noPadding gap="S">
      {#each datasources as datasource}
        <div class="datasource">
          <div class="header">
            {#if datasource.iconComponent}
              <svelte:component
                this={datasource.iconComponent}
                width="18"
                height="18"
              />
            {:else}
              <i
                class={datasource.iconClass}
                style="font-size: 18px; color: {datasource.iconColor};"
              ></i>
            {/if}
            <h2>{datasource.name}</h2>
          </div>
          <!-- List all tables -->
          {#each datasource.tablesAndViews as tableOrView}
            {@const selected = selectedTablesAndViews.some(
              selected => selected.id === tableOrView.id
            )}
            <TableOrViewOption
              on:click={() => toggleSelection(tableOrView)}
              {selected}
              {tableOrView}
            />
          {/each}
        </div>
      {/each}
    </Layout>
  {:else}
    <Body size="M">
      You have no data tables.
      <p class="no-tables">
        Go to the
        <Link size="L" href={dataUrl || null}>Data section</Link>
        to connect your database.
      </p></Body
    >
  {/if}
</ModalContent>

<style>
  .datasource {
    padding-bottom: 15px;
    display: flex;
    flex-direction: column;
    grid-gap: var(--spacing-s);
    max-width: 100%;
    min-width: 0;
  }

  .datasource:last-child {
    padding-bottom: 0;
  }

  .header {
    display: flex;
    align-items: center;
    padding-bottom: var(--spacing-m);
  }

  .header :global(svg) {
    flex-shrink: 0;
  }

  .header h2 {
    padding-top: 1px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    font-size: 14px;
    font-weight: 400;
    margin: 0;
    margin-left: 10px;
  }

  .no-tables :global(.spectrum-Link) {
    font-weight: 900;
    color: inherit;
    text-decoration: none;
  }

  .no-tables :global(.spectrum-Link:hover),
  .no-tables :global(.spectrum-Link:focus) {
    text-decoration: none;
  }
</style>
