import { writable } from "svelte/store"

export { admin } from "./admin"
export { appCreationStore } from "./appCreation"
export { appsStore, enrichedApps, sortBy } from "./apps"
export { auth } from "./auth"
export { backups } from "./backups"
export { bannerStore } from "./banners"
export { clientAppsStore } from "./clientApps"
export { email } from "./email"
export { menu } from "./menu"
export { navigation } from "./navigation"
export { oidc } from "./oidc"
export { organisation } from "./organisation"
export { templates } from "./templates"
export { temporalStore } from "./temporal"
export { themeStore } from "./theme"
export { users } from "./users"

export const sideBarCollapsed = writable(false)
